[package]
name = "auction_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
dotenvy = "0.15"
serde = { version = "1", features = [ "derive" ] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres" ] }
tokio = { version = "1", features = [ "full" ] }

