services:
  db:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 8000:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auction-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

networks:
  auction-network:
    driver: bridge

volumes:
  postgres-data: